# Generated by Django 6.0.5 on 2026-07-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('merchants', '0017_storeitem_quantity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spendingrecord',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_spendings', to='merchants.storeprofile'),
        ),
    ]
