# Generated by Django 6.0.5 on 2026-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/thumbnails/'),
        ),
    ]
