# Generated by Django 6.0.5 on 2026-07-11 08:44

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_thumbnail"),
    ]

    operations = [TrigramExtension()]
