# Generated by Django 6.0.5 on 2026-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20260711_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('MAMAK', 'Mamak'), ('NASI_KANDAR', 'Nasi Kandar'), ('MALAYSIAN', 'Malaysian'), ('KOPITIAM', 'Kopitiam'), ('CHINESE', 'Chinese'), ('JAPANESE', 'Japanese'), ('KOREAN', 'Korean'), ('FUSION', 'Fusion'), ('INDONESIAN', 'Indonesian'), ('MEXICAN', 'Mexican'), ('MEDITERRANEAN', 'Mediterranean')], default='', max_length=20),
        ),
    ]
