# Generated by Django 6.0.5 on 2026-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_cuisine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('MAMAK', 'Mamak'), ('NASI_KANDAR', 'Nasi Kandar'), ('MALAYSIAN', 'Malaysian'), ('KOPITIAM', 'Kopitiam'), ('CHINESE', 'Chinese'), ('JAPANESE', 'Japanese'), ('KOREAN', 'Korean'), ('FUSION', 'Fusion'), ('INDONESIAN', 'Indonesian'), ('MEXICAN', 'Mexican'), ('MEDITERRANEAN', 'Mediterranean'), ('HEALTHY', 'Healthy')], default='', max_length=20),
        ),
    ]
