# Generated by Django 6.0.5 on 2026-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_itemcategory_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='contains_nuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='eco_packaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='locally_sourced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='merchants/items'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
