# Generated by Django 6.0.5 on 2026-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_storeitem_calories_storeitem_contains_nuts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='halal',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='vegan',
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
