# Generated by Django 6.0.5 on 2026-06-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_remove_storeitem_halal_remove_storeitem_vegan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='General description for customers.')),
                ('promotion_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FLAT_AMOUNT', 'Flat Amount Discount'), ('FREE_ITEM', 'Free Item with Purchase'), ('BUNDLE', 'Bundle Deal')], default='PERCENTAGE', max_length=20)),
                ('promotion_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount OR the total fixed price of the bundle.', max_digits=10, null=True)),
                ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bundle_description', models.TextField(blank=True, help_text="Extra info about the bundle (e.g., 'Serves 2-3 pax').")),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle_items', models.ManyToManyField(blank=True, help_text='Select the actual items included in this bundle.', related_name='bundled_promotions', to='merchants.storeitem')),
                ('eligible_items', models.ManyToManyField(blank=True, help_text='Items this promo applies to. Leave blank for store-wide.', related_name='eligible_promotions', to='merchants.storeitem')),
                ('reward_item', models.ForeignKey(blank=True, help_text='The single item given away for free.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewarded_promotions', to='merchants.storeitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='merchants.storeprofile')),
            ],
        ),
    ]
