# Generated by Django 6.0.5 on 2026-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0009_storeinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
