# Generated by Django 6.0.5 on 2026-07-11 11:29

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0011_storeprofile_image"),
    ]

    operations = [
        VectorExtension(),
    ]
