# Generated by Django 6.0.5 on 2026-07-11 11:48

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0012_auto_20260711_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
