# Generated by Django 6.0.5 on 2026-07-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0013_storeitem_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
