# Generated by Django 6.0.5 on 2026-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0014_storeprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='unit_size',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
