# Generated by Django 6.0.5 on 2026-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0015_storeitem_unit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('MAMAK', 'Mamak'),
                    ('NASI_KANDAR', 'Nasi Kandar'),
                    ('MALAYSIAN', 'Malaysian'),
                    ('KOPITIAM', 'Kopitiam'),
                    ('CHINESE', 'Chinese'),
                    ('JAPANESE', 'Japanese'),
                    ('KOREAN', 'Korean'),
                    ('FUSION', 'Fusion'),
                    ('INDONESIAN', 'Indonesian'),
                    ('MEXICAN', 'Mexican'),
                    ('MEDITERRANEAN', 'Mediterranean'),
                    ('HEALTHY', 'Healthy'),
                    ('VEGETARIAN', 'Vegetarian'),
                    ('SUPERMARKET', 'Supermarket'),
                    ('CONVENIENCE', 'Convenience Store'),
                    ('SPECIALTY', 'Specialty Mart'),
                ],
                default='',
                max_length=40,
            ),
        ),
    ]
