# Generated by Django 6.0.5 on 2026-05-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_merchant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreProfile',
        ),
    ]
