# Generated by Django 6.0.5 on 2026-07-18 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='budget_monthly',
            new_name='dine_in_budget',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grocery_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_goal',
            field=models.CharField(blank=True, choices=[('maintain_weight', 'Maintain Weight'), ('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('general_health', 'General Health')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spending_alert_percent',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('nuts', 'Nuts'), ('dairy', 'Dairy'), ('gluten', 'Gluten'), ('shellfish', 'Shellfish'), ('eggs', 'Eggs'), ('soy', 'Soy')], max_length=20), blank=True, default=list, help_text='List of user allergies'),
        ),
    ]
