# Generated by Django 6.0.5 on 2026-07-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_budget_monthly_userprofile_dine_in_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
