# Generated by Django 6.0.5 on 2026-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_target_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
