# Generated by Django 6.0.5 on 2026-07-25 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_is_vegetarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_cuisines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MAMAK', 'Mamak'), ('NASI_KANDAR', 'Nasi Kandar'), ('MALAYSIAN', 'Malaysian'), ('KOPITIAM', 'Kopitiam'), ('CHINESE', 'Chinese'), ('JAPANESE', 'Japanese'), ('KOREAN', 'Korean'), ('FUSION', 'Fusion'), ('INDONESIAN', 'Indonesian'), ('MEXICAN', 'Mexican'), ('MEDITERRANEAN', 'Mediterranean'), ('HEALTHY', 'Healthy'), ('VEGETARIAN', 'Vegetarian')], max_length=30), blank=True, default=list, help_text="List of user's preferred cuisines"),
        ),
    ]
