# Generated by Django 6.0.5 on 2026-07-25 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_preferred_cuisines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_cuisines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mamak', 'Mamak'), ('nasi_kandar', 'Nasi Kandar'), ('malaysian', 'Malaysian'), ('kopitiam', 'Kopitiam'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('fusion', 'Fusion'), ('indonesian', 'Indonesian'), ('mexican', 'Mexican'), ('mediterranean', 'Mediterranean'), ('healthy', 'Healthy'), ('vegetarian', 'Vegetarian')], max_length=30), blank=True, default=list, help_text="List of user's preferred cuisines"),
        ),
    ]
